CREATE DATABASE IF NOT EXISTS ErrorTrack;
USE ErrorTrack;

CREATE TABLE IF NOT EXISTS aluno (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  materia VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);